# GraalVM build and native test.
name: GraalVM CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  ANT_OPTS: -Djava.security.manager=allow

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test GVM 22, ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: graalvm/setup-graalvm@2911b2304bee2c2f59b9a67bf45f025a6b6de4b1 # v1.2.2
        with:
          java-version: '22'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Linux requirements
        run: sudo apt-get -y install texinfo
      - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      - name: "Build: Compile & Install JNA"
        run: ant && ant install
      - name: "Build: Native Images (Dynamic JNI)"
        run: ant nativeImage && ant nativeRun
      - name: "Build: Native Image (Static JNI)"
        run: ant nativeImageStatic && ant nativeRunStatic
