# GraalVM build and native test.
name: GraalVM CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  ANT_OPTS: -Djava.security.manager=allow

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test GVM 22, ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: graalvm/setup-graalvm@22cc13fe88ef133134b3798e128fb208df55e1f5 # v1.2.3
        with:
          java-version: '22'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Linux requirements
        run: sudo apt-get -y install texinfo
      - uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1
      - name: "Build: Compile & Install JNA"
        run: ant && ant install
      - name: "Build: Native Images (Dynamic JNI)"
        run: ant nativeImage && ant nativeRun
      - name: "Build: Native Image (Static JNI)"
        run: ant nativeImageStatic && ant nativeRunStatic
