# GraalVM build and native test.
name: GraalVM CI (Reusable)

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'The operating system to run the tests on'
        default: 'ubuntu-latest'
        type: string
      java:
        description: 'The Java version to run the tests with'
        default: 21
        type: number
  workflow_call:
    inputs:
      runner:
        description: 'The operating system to run the tests on'
        default: 'ubuntu-latest'
        type: string
      java:
        description: 'The Java version to run the tests with'
        default: 21
        type: number
  push:
    branches:
      - master

permissions:
  contents: read

env:
  ANT_OPTS: -Djava.security.manager=allow

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    name: Test GVM ${{ inputs.java }}, ${{ inputs.runner }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: graalvm/setup-graalvm@2f25c0caae5b220866f732832d5e3e29ff493338 # v1.2.1
        with:
          java-version: '${{ inputs.java }}'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Linux requirements
        if: contains(inputs.runner, 'ubuntu')
        run: sudo apt-get -y install texinfo
      - name: macOS requirements
        if: contains(inputs.runner, 'macos')
        run: |
          brew update
          brew install automake --force
          brew install libtool --force
          brew install texinfo --force
      - uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
      - name: "Build: Native Image"
        run: ant dist && ant install && ant nativeImage && ant nativeRun
