# Build native library for mac OS
name: mac OS native libraries

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-native-darwin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [21]
        os: [macos-latest]
    name: Build native libraries for mac OS / darwin

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: macOS requirements
        if: contains(matrix.os, 'macos')
        run: |
          brew update
          brew install automake --force
          brew install libtool --force
          brew install texinfo --force
      - name: Build native code
        run: |
          ant -Dos.prefix=darwin-aarch64
          ant -Dos.prefix=darwin-x86-64
      - name: Upload mac OS binaries
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: darwin-native
          path: |
            lib/native/darwin-aarch64.jar
            lib/native/darwin-x86-64.jar